// resources/js/Components/Interrogation/PhaseStepper.vue
<script setup>
import { computed } from 'vue';
import { Check } from 'lucide-vue-next';

const props = defineProps({
    phase: {
        type: Number,
        required: true,
    },
});

const steps = [
    { label: 'Setup' },
    { label: 'Tech Stack' },
    { label: 'Discovery' },
    { label: 'Interrogation' },
    { label: 'Summary' },
    { label: 'Planning' },
    { label: 'Rules' },
    { label: 'Tasks' },
    { label: 'Build' },
];

const normalizedPhase = computed(() => {
    const phase = Number(props.phase ?? 0);
    if (phase <= 1) {
        return 0;
    }

    return phase - 1;
});

const stateFor = (stepIndex) => {
    if (stepIndex < normalizedPhase.value) {
        return 'done';
    }

    if (stepIndex === normalizedPhase.value) {
        return 'active';
    }

    return 'future';
};

const circleClass = (stepIndex) => {
    const state = stateFor(stepIndex);

    if (state === 'done') {
        return 'bg-success text-success-foreground border-success';
    }

    if (state === 'active') {
        return 'bg-primary text-primary-foreground border-primary ring-4 ring-primary/20';
    }

    return 'border-2 border-muted-foreground/30 bg-card text-muted-foreground';
};

const labelClass = (stepIndex) => {
    const state = stateFor(stepIndex);

    if (state === 'done') {
        return 'text-success';
    }

    if (state === 'active') {
        return 'text-primary';
    }

    return 'text-muted-foreground';
};

const connectorClass = (stepIndex) => {
    return stepIndex < normalizedPhase.value ? 'bg-success' : 'bg-muted-foreground/25';
};
</script>

<template>
    <div class="overflow-x-auto">
        <div class="flex min-w-[700px] items-start justify-between py-1">
            <template v-for="(step, index) in steps" :key="step.label">
                <div class="flex flex-1 items-start last:flex-none">
                    <div class="flex flex-col items-center gap-1.5">
                        <div class="flex h-7 w-7 items-center justify-center rounded-full border text-[12px] font-semibold transition-all" :class="circleClass(index)">
                            <Check v-if="stateFor(index) === 'done'" class="h-3.5 w-3.5" />
                            <span v-else>{{ index + 1 }}</span>
                        </div>
                        <span class="whitespace-nowrap text-[11px] font-medium" :class="labelClass(index)">
                            {{ step.label }}
                        </span>
                    </div>

                    <div v-if="index < steps.length - 1" class="mx-2 mt-[13px] h-0.5 flex-1 rounded-full" :class="connectorClass(index)" />
                </div>
            </template>
        </div>
    </div>
</template>

// figma/src/app/components/discovery-wizard/phase-stepper.tsx
import { Check } from "lucide-react";
import type { Phase } from "./types";

interface PhaseStepperProps {
  phases: Phase[];
  onPhaseClick: (id: number) => void;
}

export function PhaseStepper({ phases, onPhaseClick }: PhaseStepperProps) {
  return (
    <div className="bg-card border border-border rounded-lg p-4 mb-4 overflow-x-auto">
      <div className="flex items-center justify-between min-w-[700px]">
        {phases.map((phase, i) => {
          const isCompleted = phase.status === "completed";
          const isActive = phase.status === "active";
          const isFuture = phase.status === "future";
          const isLast = i === phases.length - 1;

          return (
            <div key={phase.id} className="flex items-center flex-1 last:flex-none">
              {/* Circle + label */}
              <button
                onClick={() => onPhaseClick(phase.id)}
                className="flex flex-col items-center gap-1.5 group cursor-pointer"
                disabled={isFuture}
              >
                <div
                  className={`w-7 h-7 rounded-full flex items-center justify-center transition-all ${
                    isCompleted
                      ? "bg-success text-success-foreground"
                      : isActive
                      ? "bg-primary text-primary-foreground ring-4 ring-primary/20"
                      : "border-2 border-muted-foreground/30 text-muted-foreground"
                  }`}
                  style={{ fontSize: "12px", fontWeight: 600 }}
                >
                  {isCompleted ? (
                    <Check className="w-3.5 h-3.5" />
                  ) : (
                    phase.id
                  )}
                </div>
                <span
                  className={`whitespace-nowrap transition-colors ${
                    isCompleted
                      ? "text-success"
                      : isActive
                      ? "text-primary"
                      : "text-muted-foreground"
                  }`}
                  style={{ fontSize: "11px", fontWeight: 500 }}
                >
                  {phase.label}
                </span>
              </button>

              {/* Connecting line */}
              {!isLast && (
                <div className="flex-1 mx-2 mt-[-18px]">
                  <div
                    className={`h-0.5 w-full rounded-full ${
                      isCompleted
                        ? "bg-success"
                        : "bg-muted-foreground/20"
                    }`}
                  />
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
