// resources/js/Components/Interrogation/StatsPanel.vue
<script setup>
import { computed } from 'vue';
import { isAnswerableQuestionEvent, normalizeQuestionCategory } from '@/Components/Interrogation/questionPresentation';

const props = defineProps({
    session: {
        type: Object,
        required: true,
    },
    events: {
        type: Array,
        default: () => [],
    },
});

const questionCount = computed(() => props.events.filter((event) => isAnswerableQuestionEvent(event)).length);
const answerCount = computed(() => props.events.filter((event) => event.event_type === 'answer').length);

const categories = computed(() => {
    const values = new Set();

    props.events.forEach((event) => {
        if (isAnswerableQuestionEvent(event) && typeof event.payload?.category === 'string' && event.payload.category !== '') {
            const normalized = normalizeQuestionCategory(event.payload.category);
            if (normalized !== '') {
                values.add(normalized);
            }
        }
    });

    return Array.from(values);
});

const latestProgress = computed(() => {
    const questions = props.events.filter((event) => isAnswerableQuestionEvent(event));

    if (questions.length === 0) {
        return 0;
    }

    return Number(questions[questions.length - 1]?.payload?.progress_estimate ?? 0);
});

const elapsedLabel = computed(() => {
    const startedAt = props.session?.started_at;

    if (!startedAt) {
        return 'Not started';
    }

    const ms = Date.now() - new Date(startedAt).getTime();
    if (!Number.isFinite(ms) || ms < 0) {
        return 'Unknown';
    }

    const minutes = Math.floor(ms / 60000);
    const hours = Math.floor(minutes / 60);

    if (hours > 0) {
        return `${hours}h ${minutes % 60}m`;
    }

    return `${minutes}m`;
});

const statusClass = computed(() => {
    const status = String(props.session?.status ?? '').toLowerCase();
    const map = {
        setup: 'bg-muted text-muted-foreground',
        discovering: 'bg-primary/10 text-primary',
        interrogating: 'bg-primary/10 text-primary',
        summarizing: 'bg-warning/10 text-warning',
        planning: 'bg-warning/10 text-warning',
        build_rules: 'bg-warning/10 text-warning',
        build_tasks: 'bg-primary/10 text-primary',
        build_executing: 'bg-primary/10 text-primary',
        paused: 'bg-muted text-muted-foreground',
        completed: 'bg-success/10 text-success',
        failed: 'bg-destructive/10 text-destructive',
    };

    return map[status] ?? 'bg-muted text-muted-foreground';
});

const categoryClass = (index) => {
    const classes = [
        'bg-primary/10 text-primary',
        'bg-warning/10 text-warning',
        'bg-success/10 text-success',
        'bg-destructive/10 text-destructive',
    ];

    return classes[index % classes.length];
};
</script>

<template>
    <div class="space-y-3 rounded-lg border border-border bg-card p-4">
        <h3 class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Stats</h3>

        <dl class="space-y-2 text-sm">
            <div class="flex justify-between"><dt class="text-muted-foreground">Questions</dt><dd class="font-medium text-foreground">{{ questionCount }}</dd></div>
            <div class="flex justify-between"><dt class="text-muted-foreground">Answers</dt><dd class="font-medium text-foreground">{{ answerCount }}</dd></div>
            <div class="flex justify-between"><dt class="text-muted-foreground">Elapsed</dt><dd class="font-medium text-foreground">{{ elapsedLabel }}</dd></div>
            <div class="flex justify-between items-center">
                <dt class="text-muted-foreground">Status</dt>
                <dd class="inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-medium capitalize" :class="statusClass">{{ session.status }}</dd>
            </div>
        </dl>

        <div>
            <div class="mb-1 flex items-center justify-between text-xs text-muted-foreground">
                <span>Progress</span>
                <span>{{ latestProgress }}%</span>
            </div>
            <div class="h-1.5 rounded bg-muted/80">
                <div class="h-1.5 rounded bg-primary" :style="{ width: `${Math.max(0, Math.min(100, latestProgress))}%` }" />
            </div>
        </div>

        <div class="border-t border-border pt-3">
            <p class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Categories</p>
            <div v-if="categories.length > 0" class="mt-2 flex flex-wrap gap-1.5">
                <span
                    v-for="(category, index) in categories"
                    :key="category"
                    class="inline-flex items-center rounded-full px-2 py-0.5 text-[11px] font-medium"
                    :class="categoryClass(index)"
                >
                    {{ category }}
                </span>
            </div>
            <p v-else class="mt-1 text-xs text-muted-foreground">No categories yet</p>
        </div>
    </div>
</template>

// figma/src/app/components/discovery-wizard/stats-panel.tsx
import { Card, CardContent } from "../ui/card";
import { Progress } from "../ui/progress";

interface StatsPanelProps {
  questions: number;
  answers: number;
  elapsed: string;
  status: string;
  progress: number;
  categories: string[];
}

const statusColorMap: Record<string, string> = {
  setup: "bg-muted text-muted-foreground",
  discovering: "bg-primary/10 text-primary",
  interrogating: "bg-primary/10 text-primary",
  summarizing: "bg-warning/10 text-warning",
  planning: "bg-warning/10 text-warning",
  build_rules: "bg-warning/10 text-warning",
  build_tasks: "bg-primary/10 text-primary",
  build_executing: "bg-primary/10 text-primary",
  completed: "bg-success/10 text-success",
  failed: "bg-destructive/10 text-destructive",
  paused: "bg-warning/10 text-warning",
};

const categoryColors = [
  "bg-primary/10 text-primary",
  "bg-destructive/10 text-destructive",
  "bg-warning/10 text-warning",
  "bg-[#7c3aed]/10 text-[#7c3aed]",
  "bg-success/10 text-success",
];

export function StatsPanel({
  questions,
  answers,
  elapsed,
  status,
  progress,
  categories,
}: StatsPanelProps) {
  return (
    <Card className="border border-border shadow-none">
      <CardContent className="p-4">
        <h4
          className="uppercase tracking-wider text-muted-foreground mb-3"
          style={{ fontSize: "11px", fontWeight: 600 }}
        >
          Stats
        </h4>
        <div className="space-y-2.5">
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground" style={{ fontSize: "13px" }}>
              Questions
            </span>
            <span className="text-foreground" style={{ fontSize: "13px", fontWeight: 500 }}>
              {questions}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground" style={{ fontSize: "13px" }}>
              Answers
            </span>
            <span className="text-foreground" style={{ fontSize: "13px", fontWeight: 500 }}>
              {answers}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground" style={{ fontSize: "13px" }}>
              Elapsed
            </span>
            <span className="text-foreground" style={{ fontSize: "13px", fontWeight: 500 }}>
              {elapsed}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground" style={{ fontSize: "13px" }}>
              Status
            </span>
            <span
              className={`inline-flex items-center px-2 py-0.5 rounded-full ${statusColorMap[status] || "bg-muted text-muted-foreground"}`}
              style={{ fontSize: "11px", fontWeight: 500 }}
            >
              {status}
            </span>
          </div>
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-muted-foreground" style={{ fontSize: "13px" }}>
                Progress
              </span>
              <span className="text-foreground" style={{ fontSize: "13px", fontWeight: 500 }}>
                {progress}%
              </span>
            </div>
            <Progress value={progress} className="h-1.5" />
          </div>
        </div>

        {/* Categories */}
        <div className="mt-4 pt-3 border-t border-border">
          <h4
            className="uppercase tracking-wider text-muted-foreground mb-2"
            style={{ fontSize: "11px", fontWeight: 600 }}
          >
            Categories
          </h4>
          {categories.length === 0 ? (
            <p className="text-muted-foreground" style={{ fontSize: "12px" }}>
              No categories yet
            </p>
          ) : (
            <div className="flex flex-wrap gap-1.5">
              {categories.map((cat, i) => (
                <span
                  key={cat}
                  className={`inline-flex items-center px-2 py-0.5 rounded-full ${categoryColors[i % categoryColors.length]}`}
                  style={{ fontSize: "11px", fontWeight: 500 }}
                >
                  {cat}
                </span>
              ))}
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
